### PR TITLE
Set default exporter list from config

### PR DESCRIPTION
**Pull request by kfdm**
This allows a team to set the commonly used exporters in the config file.

```yml
default_exporters:
    node: 9100
    nginx: 9113
    mysqld: 9104
    apache: 9117
```

### CODE REVIEW

**Comment by tokuhirom** [comment]
:+

**Comment by tokuhirom** [comment]
👍

**Comment by wyukawa** [comment]
Could you resolve confict?

**Comment by kfdm** [comment]
That should fix the conflict.

**Pull request merged**
