### PR TITLE
Release 0.66

### PR DESCRIPTION
**Pull request by kfdm**
Cutting a final release from me.

### CODE REVIEW

**Comment by vincent-olivert-riera** [comment]
@kfdm , which commit are you going to chose for the tag?
I see that the changes for the [silence list modal](https://github.com/line/promgen/pull/539) are not included in the changelog.

**Comment by kfdm** [comment]
> @kfdm , which commit are you going to chose for the tag? I see that the changes for the [silence list modal](https://github.com/line/promgen/pull/539) are not included in the changelog.

I think the commit was included, but the commit messages were not formatted correctly so it was missed when creating the changelog.

**Comment by vincent-olivert-riera** [comment]
> > @kfdm , which commit are you going to chose for the tag? I see that the changes for the [silence list modal](https://github.com/line/promgen/pull/539) are not included in the changelog.
> 
> I think the commit was included, but the commit messages were not formatted correctly so it was missed when creating the changelog.
> 
> It's not a major change, so I'm not going to spend time trying to redo the changelog.

I see. No problem at all 👍

**Review by vincent-olivert-riera — APPROVED** [review]
LGTM

**Comment by kfdm** [comment]
Not sure why the license/cla is stuck but this has happened in the past . . .

**Comment by vincent-olivert-riera** [comment]
> Not sure why the license/cla is stuck but this has happened in the past . . .

Uhm..., just in case, could you check https://cla-assistant.io/line/promgen again?

**Comment by kfdm** [comment]
Nothing has changed. I did that years ago when it was first enabled ^^;

**Comment by vincent-olivert-riera** [comment]
> Confirmed that link and nothing has changed

I will try to pass that information to the relevant people to see what is going on.

I have merged the PR for you.

**Pull request merged**
