### PR TITLE
[IMPROVEMENT] Test metrics validity when testing Exporter

### PR DESCRIPTION
**Pull request by kfdm**
When using the 'test' button for an exporter, we previously *only* checked the status code and assumed things were good. It is very possible for an incorrect endpoint to be registered, so we should ensure that the registered endpoint produces correct Prometheus metrics.

Right now, we will return a somewhat *developer* like output, but I expect to make the output more user friendly as we cleanup some of our internal test URLs.

test exporter

### CODE REVIEW

**Review by vincent-olivert-riera — APPROVED** [review]
Code changes look good to me.
Tested in my local env and working fine.

Approved 👍

**Comment by vincent-olivert-riera** [comment]
@kfdm ⬇️ 
> license/cla Expected — Waiting for status to be reported

**Comment by kfdm** [comment]
> @kfdm ⬇️
> 
> > license/cla Expected — Waiting for status to be reported

Yeah, was trying to see why that's stuck, but I'm a bit of a loss. I'm not actually the one that configured that either 🤔

**Comment by vincent-olivert-riera** [comment]
> > @kfdm ⬇️
> > > license/cla Expected — Waiting for status to be reported
> 
> Yeah, was trying to see why that's stuck, but I'm a bit of a loss. I'm not actually the one that configured that either 🤔

Me neither, since I don't even have access to the repo's settings.
Do you have anything left to sign in here? https://cla-assistant.io/line/promgen

**Pull request merged**
